id: d6_simpletest_settings
label: Simpletest configuration
migration_tags:
  - Drupal 6
source:
  plugin: variable
  variables:
    - simpletest_clear_results
    - simpletest_httpauth_method
    - simpletest_httpauth_password
    - simpletest_httpauth_username
    - simpletest_verbose
process:
  clear_results: simpletest_clear_results
  'httpauth/method': simpletest_httpauth_method
  'httpauth/password': simpletest_httpauth_password
  'httpauth/username': simpletest_httpauth_username
  verbose: simpletest_verbose
destination:
  plugin: config
  config_name: simpletest.settings
