content_roles:
  creator:
    enabled: true
    label: '? creator'
    permissions:
      - 'create ? content'
      - 'edit own ? content'
      - 'view ? revisions'
      - 'view own unpublished content'
      - 'create url aliases'
      - 'access panels in-place editing'
      - 'change layouts in place editing'
      - 'administer panelizer node ? content'
      - 'administer panelizer node ? layout'
      - 'use text format rich_text'
      - 'access media_browser entity browser pages'
      - 'access image_browser entity browser pages'
  reviewer:
    enabled: true
    label: '? reviewer'
    permissions:
      - 'access content overview'
      - 'edit any ? content'
      - 'delete any ? content'
_core:
  default_config_hash: 1D1VGtT9meAUY7K8zDShQJ8B6fDyUPzoAlUBXTiIWBU
