#!/bin/bash

set -eo pipefail

#
# This script deletes any fixtures that are no longer needed.
#
# Note that we allow the "ci-BUILD_NUMBER" and "pr-PULL_REQUEST_NUMBER"
# multidev sites to persist until the next time the 'prepare' or
# 'merge-master' scripts (respectively) are called.
#

if [[ ${CI_BRANCH} != "master" && -z ${PR_NUMBER} ]];
then
  echo -e "CI will only deploy to Pantheon if on the master branch or creating a pull requests.\n"
  exit 0;
fi

echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo "Clean up on site: $TERMINUS_SITE.$TERMINUS_ENV"
echo "::::::::::::::::::::::::::::::::::::::::::::::::"
echo

# Clear site cache
terminus -n env:clear-cache $TERMINUS_SITE.$TERMINUS_ENV